-- Auth flow: run in Supabase SQL editor if columns/tables are missing.
-- Adjust names if your schema already differs.

-- User columns (ERD)
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS email text;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS email_verified_at timestamptz;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS last_login_at timestamptz;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS password_changed_at timestamptz;
ALTER TABLE "user" ADD COLUMN IF NOT EXISTS updated_at timestamptz;

CREATE UNIQUE INDEX IF NOT EXISTS user_email_lower_unique ON "user" (lower(email))
  WHERE email IS NOT NULL;

CREATE TABLE IF NOT EXISTS email_verification_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id bigint NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  token_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_email_verification_token_hash ON email_verification_tokens (token_hash);

CREATE TABLE IF NOT EXISTS password_reset_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  user_id bigint NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  token_hash text NOT NULL,
  expires_at timestamptz NOT NULL,
  used_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_password_reset_token_hash ON password_reset_tokens (token_hash);
